=== shellybar/fMRI/common/src/main/resources/unit.dtd
<!ELEMENT unit (description?, parameters?, prerequisites?)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT parameters (file-parameter*, string-parameter*)>
<!ELEMENT string-parameter (name, display)>
<!ELEMENT file-parameter (name, display)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT display (#PCDATA)>
<!ELEMENT prerequisites (prerequisite+)>
<!ELEMENT prerequisite EMPTY>

<!ATTLIST unit id CDATA #REQUIRED>

=== shellybar/fMRI/data/unit_settings/unit_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE unit SYSTEM "unit.dtd">-->

<unit id="1">
    <description>Reads a file and writes the same file to a new location</description>
    <parameters>
        <file-parameter>
            <name>srcFile</name>
            <display>Source file path</display>
        </file-parameter>
        <file-parameter>
            <name>destFile</name>
            <display>Destination file path</display>
        </file-parameter>
    </parameters>
</unit>
